### ISSUE TITLE
Hints for converting ternary to if and back are missing

### ISSUE THREAD

**Issue by Tuupertunut** [markiewb/nb-additional-hints#78]
Using 1.6.0.10, the hints for converting between ternary and if statements are missing. There might be any number of other missing hints I'm not aware of. Here's a picture of my hints:
![image](https://cloud.githubusercontent.com/assets/1782631/21951167/ac748306-da0b-11e6-85dc-acdf355dea65.png)

**Comment by markiewb** [comment]
Thanks for noticing. I accidentally removed it in https://github.com/markiewb/nb-additional-hints/commit/9dc0b9c

I will reintroduce the hint.

**Comment by markiewb** [comment]
Fixed in 1.6.1. I uploaded a new version to the plugin center. But it still has to be verified. So wait a few days.
